//
//  DerivedDataCommand.swift
//  Nnpurge
//
//  Created by Nikolai Nobadi on 10/26/25.
//

import Foundation
import CodePurgeKit
import ArgumentParser

extension Nnpurge {
    struct DerivedDataCommand: ParsableCommand {
        static let configuration = CommandConfiguration(
            commandName: "derived-data",
            abstract: "Manage derived data generated by Xcode",
            subcommands: [
                Delete.self,
                Path.self
            ]
        )
    }
}


// MARK: - Delete
extension Nnpurge.DerivedDataCommand {
    struct Delete: ParsableCommand {
        static let configuration = CommandConfiguration(
            abstract: "Deletes derived data generated by Xcode"
        )
        
        @Flag(name: .shortAndLong, help: "Deletes all derived data folders.")
        var all: Bool = false
        
        func run() throws {
            let store = Nnpurge.makeUserDefaults()
            let picker = Nnpurge.makePicker()
            let service = Nnpurge.makeDerivedDataService(path: store.loadDerivedDataPath())
            let controller = DerivedDataController(store: store, picker: picker, service: service)

            try controller.deleteDerivedData(deleteAll: all)
        }
    }
}


// MARK: - Path
extension Nnpurge.DerivedDataCommand {
    struct Path: ParsableCommand {
        static let configuration = CommandConfiguration(
            abstract: "View or set the derived data folder path"
        )

        @Option(name: .shortAndLong, help: "Set a custom path for the derived data folder.")
        var set: String?

        @Flag(name: .shortAndLong, help: "Reset to the default derived data path.")
        var reset: Bool = false

        func run() throws {
            let store = Nnpurge.makeUserDefaults()
            let picker = Nnpurge.makePicker()
            let service = Nnpurge.makeDerivedDataService(path: store.loadDerivedDataPath())
            let controller = DerivedDataController(store: store, picker: picker, service: service)

            let message = controller.managePath(set: set, reset: reset)
            print(message)
        }
    }
}
