//
//  DerivedDataCommand.swift
//  Nnpurge
//
//  Created by Nikolai Nobadi on 10/26/25.
//

import Foundation
import CodePurgeKit
import ArgumentParser

extension Nnpurge {
    struct DerivedDataCommand: ParsableCommand {
        static let configuration = CommandConfiguration(
            commandName: "derived-data",
            abstract: "Manage derived data generated by Xcode",
            subcommands: [
                Delete.self
            ]
        )
    }
}


// MARK: - Delete
extension Nnpurge.DerivedDataCommand {
    struct Delete: ParsableCommand {
        static let configuration = CommandConfiguration(
            abstract: "Deletes derived data generated by Xcode"
        )
        
        @Flag(name: .shortAndLong, help: "Deletes all derived data folders.")
        var all: Bool = false
        
        func run() throws {
            let picker = Nnpurge.makePicker()
            let store = Nnpurge.makeUserDefaults()
            let service = Nnpurge.makeDerivedDataService()
            let controller = DerivedDataController(picker: picker, service: service)

            try controller.deleteDerivedData(deleteAll: all)
        }
    }
}


// MARK: - Extension Dependencies
private extension DerivedDataStore {
    func loadDerivedDataPath() -> String {
        let path = string(forKey: .derivedDataPathKey) ?? "~/Library/Developer/Xcode/DerivedData"
        
        return NSString(string: path).expandingTildeInPath
    }
}

private extension String {
    static var derivedDataPathKey: String {
        return "derivedDataPathKey"
    }
}
