//
//  DerivedDataCommand.swift
//  Nnpurge
//
//  Created by Nikolai Nobadi on 10/26/25.
//

import Foundation
import CodePurgeKit
import ArgumentParser

extension Nnpurge {
    struct DerivedDataCommand: ParsableCommand {
        static let configuration = CommandConfiguration(
            commandName: "derived-data",
            abstract: "Manage derived data generated by Xcode",
            subcommands: [
                Delete.self,
                Path.self
            ]
        )
    }
}


// MARK: - Delete
extension Nnpurge.DerivedDataCommand {
    struct Delete: ParsableCommand {
        static let configuration = CommandConfiguration(
            abstract: "Deletes derived data generated by Xcode"
        )
        
        @Flag(name: .shortAndLong, help: "Deletes all derived data folders.")
        var all: Bool = false
        
        func run() throws {
            let picker = Nnpurge.makePicker()
            let store = Nnpurge.makeUserDefaults()
            let service = Nnpurge.makeDerivedDataService(path: store.loadDerivedDataPath())
            let controller = DerivedDataController(picker: picker, service: service)

            try controller.deleteDerivedData(deleteAll: all)
        }
    }
}


// MARK: - Path
extension Nnpurge.DerivedDataCommand {
    struct Path: ParsableCommand {
        static let configuration = CommandConfiguration(
            abstract: "View or set the derived data folder path"
        )

        @Option(name: .shortAndLong, help: "Set a custom path for the derived data folder.")
        var set: String?

        @Flag(name: .shortAndLong, help: "Reset to the default derived data path.")
        var reset: Bool = false

        func run() throws {
            let store = Nnpurge.makeUserDefaults()

            if reset {
                store.set(nil, forKey: .derivedDataPathKey)
                print("Derived data path reset to default: ~/Library/Developer/Xcode/DerivedData")
                return
            }

            if let newPath = set {
                let expandedPath = NSString(string: newPath).expandingTildeInPath
                store.set(expandedPath, forKey: .derivedDataPathKey)
                print("Derived data path set to: \(expandedPath)")
                return
            }

            let currentPath = store.loadDerivedDataPath()
            let isDefault = store.string(forKey: .derivedDataPathKey) == nil
            print("Current derived data path: \(currentPath)")
            if isDefault {
                print("(using default)")
            }
        }
    }
}


// MARK: - Dependencies
protocol DerivedDataStore {
    func string(forKey defaultName: String) -> String?
    func set(_ value: Any?, forKey defaultName: String)
}

extension UserDefaults: DerivedDataStore {}


// MARK: - Extension Dependencies
private extension DerivedDataStore {
    func loadDerivedDataPath() -> String {
        let path = string(forKey: .derivedDataPathKey) ?? "~/Library/Developer/Xcode/DerivedData"
        
        return NSString(string: path).expandingTildeInPath
    }
}

private extension String {
    static var derivedDataPathKey: String {
        return "derivedDataPathKey"
    }
}
