//
//  nnpurge.swift
//  nnpurge
//
//  Created by Nikolai Nobadi on 6/6/25.
//

import Files
import Foundation
import SwiftPicker
import ArgumentParser

struct nnpurge: ParsableCommand {
    static let configuration = CommandConfiguration(
        abstract: "A command-line tool to clean up Xcode's derived data folders with interactive prompts for safety and precision.",
        subcommands: [
            DeleteDerivedData.self
        ]
    )
}

extension nnpurge {
    struct DeleteDerivedData: ParsableCommand {
        static let configuration = CommandConfiguration(
            commandName: "ddd",
            abstract: "Deletes derived data generated by Xcode"
        )
        
        @Flag(name: .shortAndLong, help: "Deletes all derived data folders.")
        var all: Bool = false
        
        func run() throws {
            let picker = SwiftPicker()
            var foldersToDelete = try loadDerivedDataFolders()
            
            if all {
                try picker.requiredPermission(prompt: "Are you sure you want to delete all derived data?")
            } else {
                let selection = try picker.requiredSingleSelection("What would you like to do?", items: DerivedDataAction.allCases)
                
                switch selection {
                case .deleteAll:
                    try picker.requiredPermission(prompt: "Are you sure you want to delete all derived data?")
                case .deleteSelectFolder:
                    foldersToDelete = picker.multiSelection("Select the folders to delete.", items: foldersToDelete)
                }
            }
            
            try moveFoldersToTrash(foldersToDelete)
        }
    }
}

extension nnpurge.DeleteDerivedData {
    func loadDerivedDataFolders() throws -> [Folder] {
        let derivedDataPath = "~/Library/Developer/Xcode/DerivedData"
        return try Folder(path: derivedDataPath).subfolders.map { $0 }
    }
    
    func moveFoldersToTrash(_ folders: [Folder]) throws {
        for folder in folders {
            print("Moving \(folder.name) to Trash")
            try FileManager.default.trashItem(at: folder.url, resultingItemURL: nil)
            print("\(folder.name) successfully moved to Trash")
        }
    }
}

enum DerivedDataAction: CaseIterable {
    case deleteAll, deleteSelectFolder
}

extension Folder: @retroactive DisplayablePickerItem {
    public var displayName: String {
        name
    }
}

extension DerivedDataAction: DisplayablePickerItem {
    var displayName: String {
        switch self {
        case .deleteAll:
            return "Delete all derived data folders."
        case .deleteSelectFolder:
            return "Delete selected derived data folders"
        }
    }
}
