////
////  DeleteDerivedData.swift
////  nnpurge
////
////  Created by Nikolai Nobadi on 6/17/25.
////
//
//import Foundation
//import ArgumentParser
//
//extension Nnpurge {
//    struct DeleteDerivedData: ParsableCommand {
//        static let configuration = CommandConfiguration(
//            commandName: "ddd",
//            abstract: "Deletes derived data generated by Xcode"
//        )
//        
//        @Flag(name: .shortAndLong, help: "Deletes all derived data folders.")
//        var all: Bool = false
//        
//        @Flag(name: .shortAndLong, help: "Opens the DerivedData folder.")
//        var open: Bool = false
//        
//        func run() throws {
//            if open {
//                try openDerivedDataFolder()
//                return
//            }
//
//            // TODO: - 
////            let controller = Nnpurge.makeDerivedDataController()
////            try controller.deleteDerivedData(deleteAll: all)
//        }
//    }
//}
//
//
//// MARK: - Private Methods
//private extension Nnpurge.DeleteDerivedData {
//    func openDerivedDataFolder() throws {
//        let userDefaults = Nnpurge.makeUserDefaults()
//        let defaultPath = "~/Library/Developer/Xcode/DerivedData"
//        let savedPath = userDefaults.string(forKey: "derivedDataPath") ?? defaultPath
//        let expandedPath = NSString(string: savedPath).expandingTildeInPath
//        
//        let process = Process()
//        process.executableURL = URL(fileURLWithPath: "/usr/bin/open")
//        process.arguments = [expandedPath]
//        try process.run()
//        process.waitUntilExit()
//    }
//}
