import ArgumentParser
import Files
import SwiftPicker

extension nnpurge {
    struct DeleteDerivedData: ParsableCommand {
        static let configuration = CommandConfiguration(
            commandName: "ddd",
            abstract: "Deletes derived data generated by Xcode"
        )

        @Flag(name: .shortAndLong, help: "Deletes all derived data folders.")
        var all: Bool = false

        func run() throws {
            let picker = SwiftPicker()
            var foldersToDelete = try DerivedDataManager.loadDerivedDataFolders()

            if all {
                try picker.requiredPermission(prompt: "Are you sure you want to delete all derived data?")
            } else {
                let selection = try picker.requiredSingleSelection("What would you like to do?", items: DerivedDataAction.allCases)

                switch selection {
                case .deleteAll:
                    try picker.requiredPermission(prompt: "Are you sure you want to delete all derived data?")
                case .deleteSelectFolder:
                    foldersToDelete = picker.multiSelection("Select the folders to delete.", items: foldersToDelete)
                }
            }

            try DerivedDataManager.moveFoldersToTrash(foldersToDelete)
        }
    }
}
