//
//  DeleteDerivedData.swift
//  nnpurge
//
//  Created by Nikolai Nobadi on 6/17/25.
//

import ArgumentParser
import Files
import SwiftPicker

extension nnpurge {
    /// Command that removes Xcode derived data folders.
    ///
    /// When run interactively the command will prompt the user for
    /// confirmation before deleting any folders.
    struct DeleteDerivedData: ParsableCommand {
        static let configuration = CommandConfiguration(
            commandName: "ddd",
            abstract: "Deletes derived data generated by Xcode"
        )

        @Flag(name: .shortAndLong, help: "Deletes all derived data folders.")
        var all: Bool = false

        /// Executes the deletion command based on the provided options.
        func run() throws {
            let picker = nnpurge.makePicker()
            let manager = nnpurge.makeDerivedDataManager()
            var foldersToDelete = try manager.loadDerivedDataFolders()

            if all {
                try picker.requiredPermission(prompt: "Are you sure you want to delete all derived data?")
            } else {
                let selection = try picker.requiredSingleSelection("What would you like to do?", items: DerivedDataAction.allCases)

                switch selection {
                case .deleteAll:
                    try picker.requiredPermission(prompt: "Are you sure you want to delete all derived data?")
                case .deleteSelectFolder:
                    foldersToDelete = picker.multiSelection("Select the folders to delete.", items: foldersToDelete)
                }
            }

            try manager.moveFoldersToTrash(foldersToDelete)
        }
    }
}
